[package]
name = "xv6"
version = "0.1.0"
authors = ["TODO"]

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bitfield = "0.13.2"
spin = "0.9.2"
x86 = "0.45.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
